### PR TITLE
Rename experimental_gismu/b/bekpi.yaml to gismu/b/bekpi.yaml

### PR DESCRIPTION
**Pull request by gerkubergu**

### CODE REVIEW

**Comment by gerkubergu** [comment]
Example added: {ko catlu lo bekpi be mi} / "Look at my back."

Vote called with a due date of next Monday (also {kibro} and {kanpe} will be due on Monday). Hopefully this will be easier to vote up or down than the global proposals :)

**Comment by adamlopresto** [comment]
Are all the weird quotes in the place structure some artifact of yaml? I'm not really sure why there are any quotes in there at all, actually.

 place structure: 'x1 is a/the ''back''/dorsum/''posterior'' body-part of x2 '

I feel like both this and {trixe} could use some editing of their definitions or notes, to clarify the distinction. Also, the notes for this have "Not necessarily should be at the back of the body", which is really weird English, and only seems to make the whole definition more confusing.

Maybe make the place structure "x1 is a/the dorsum/'back'/upper surface (body part) of x2" with notes "For animals that walk upright, the dorsum is the back. For animals that are typically horizontal, the dorsum is the upper surface." I'm very open to other wording. Also, should probably mention the solution to "ventral" (is it just {tolbekpi}? Why doesn't it have a word of its own?)

**Comment by durka** [comment]
Yes, the quotes are an artifact of YAML. I'm not too worried about getting the quotes mixed up during the process, we can fix them all at the end.

**Comment by solpahi** [comment]
la durka cu cusku di'e

> Example added: {ko catlu lo bekpi be mi} / "Look at my back."

About {bekpi}: I approve of the definition, but am not a big fan of its 
sound. {bajdi} seems to be the other top-scoring gismu shape for the 
same source words, but oh well.

I think that if we have one anatomical term of location, shouldn't we 
consider having the full set? On the other hand, if those are supposed 
to be fu'ivla, then so should {bekpi}.

And lastly, a possible example to show the different orientations of 
{bekpi}:

lo bekpi be lo remna cu sraji .i je lo bekpi be lo xirma cu pinta
"The backs of humans are upright, and the backs of horses are horizontal."

(or some other animal with a horizontal back)

**Comment by gerkubergu** [comment]
Added that example and short rafsi -bek- (the other choice is -bep- but pe'i -bek- is easier to say, and easier for English speakers to remember). No short terminal rafsi are available. @selpahi are you actually proposing changing it to {bajdi}? I agree that it does sound a bit prettier to my ears, though no short rafsi are available at all. There is pretty much no recorded usage but {bekpi} was the agreed-upon form in the mailing list thread.

**Comment by lagleki** [comment]
Indeed, the correct term is "dorsum". Period.
As for ventral part I couldn't find any glossing apart from what was used
in producing {betfu}.

{bekpi} is top score (see the mailing list) with mnemonics [bei](Chinese),
[bek](english), [sPIna](Russian) ...

2014-06-12 18:37 GMT+04:00 adamlopresto notifications@github.com:

**Comment by durka** [comment]
As for the "ventral" question, JVS lists lujvo dalcnita/dalgapru for dorsal/ventral respectively. But there's no usage of those either.

**Comment by durka** [comment]
Fixed notes and added cf tolbekpi.

**Pull request merged**
