### PR TITLE
Rename experimental_gismu/k/kibro.yaml to gismu/k/kibro.yaml

### PR DESCRIPTION
**Pull request by gerkubergu**

### CODE REVIEW

**Comment by durka** [comment]
Proposed examples:

{mi certu lo ka fukra'e lo selsampla lo kibro}
"I am an expert in copying source code from the Internet."

I'm finding precious little usage of kibro2 in the corpus. The best example is
{.i ku'i lo mi mensi rinka lo nu mi na se kibro}
"But, my mind causes me not to be an internet aspect."
...but I'm not sure about that translation at all.

I would assume/want kibro2 to be more like
{ti poi samca'a cu kibro lo ka benji lo datnyvei fo lo gusni tubnu seltcana}
"This computer is internetical in that it sends files over an optical fiber network."
...but I don't see usage in KZS to support me on this.

**Comment by gerkubergu** [comment]
Examples added as above: {mi certu lo ka fukra'e lo selsampla lo kibro} / "I am an expert in copying source code from the Internet." and {ti poi samca'a cu kibro lo ka benji lo datnyvei fo lo gusni tubnu seltcana} / "This computer is internetical in that it sends files over an optical fiber network."

Vote called with a due date of next Monday.

**Comment by adamlopresto** [comment]
At first (lines 2-3) it says no rafsi, but then all the definitions (except the simple English) list -kib- as a short rafsi.

**Comment by durka** [comment]
@DerSaidin check out the glosses (under each language) where it says "x1=internet", etc

@adamlopresto fixed. I think none of the experimental gismu have proposed rafsi listed as such, because of the way JVS works.

**Comment by solpahi** [comment]
> Vote called with a due date of next Monday.

kibro (-kib-) is obviously going to be official, sorry for being so sure. :)

**Comment by durka** [comment]
Yeah, usage has pretty much decided this one.

**Comment by lagleki** [comment]
Mentioning the rafsi in notes is a hack. The rafsi place should be editable.

Simple English is gonna be very special. In fact I dream of better
formalisation of definitions. Like hyperlinks to other words are to be in a
separate field. The same for famyma'o. The list can go on but not in this
project.

2014-06-12 18:26 GMT+04:00 adamlopresto notifications@github.com:

**Comment by durka** [comment]
@lagleki of course it is a hack, I assume because jbovlaste doesn't have a field for rafsi in experimental gismu. But anyway I fixed it before merging.

**Pull request merged**
